version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      # This docker image is created from the Dockerfile in
      # this repository.
      - image: ministryofjustice/cloud-platform-user-guide:1.6
        environment:
          # This is the domain on which the user guide is served
          DOMAIN: user-guide.cloud-platform.service.justice.gov.uk

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            # this SSH key must be configured in the account of the github user
            # who will be pushing changes. The corresponding private key must
            # be added to the project on circleci.com
            # Currently, this is the 'cloud-platform-moj' github user account.
            # The GitHub user must be added to the cloud-platform-user-guide
            # repository as an admin.
            - "b4:43:a7:ce:06:8d:ef:4e:11:71:de:75:65:6c:fa:a2"

      - checkout

        # Don't build and push if the latest commit only includes changes to the compiled static files.
        # This prevents circleci from going into an endless loop, where it pushes changes to docs/ and
        # then starts a new build because it sees changes to the repo. This script tests for that, and
        # exits with an error if the build should not proceed.
      - run: bin/pipeline-should-build.sh

        # Build the user guide
      - run: bundle exec middleman build --build-dir docs

        # Test the hyperlinks
      - run: htmlproofer --allow-hash-href ./docs

        # Replace docs/.nojekyll (which gets deleted during the build process) so github knows we're
        # not using jekyll. Without this, github will try to process our files, and error.
      - run: touch docs/.nojekyll

        # Replace the docs/CNAME file (which gets deleted during the build process)
      - run: echo ${DOMAIN} > docs/CNAME

        # Set git user credentials (otherwise the git push will fail)
      - run: git config credential.helper cache
      - run: git config user.email "platforms+githubuser@digital.justice.gov.uk"
      - run: git config user.name "MoJ Cloud Platform Team Machine User"

        # Add and push the compiled static files
      - run: git add docs -f
      - run: git commit -m 'Publish changes via CircleCI'
      - run: git push origin master
